### ISSUE TITLE
missing any license and any link to original work!

### ISSUE THREAD

**Issue by cenit** [carlidel/Cpp_commedia_remastered#1]
Please add at least a reference to the original work, and maybe check the license! This should be done before publishing!

http://www.physycom.unibo.it/labinfo/per_cominciare.php

btw: I like the idea VERY VERY much!

**Comment by carlidel** [comment]
Shame on me, I have to say that I always take the act of online pubblication too carelessly.
I added some notes, but I'm not sure of what kind of licence to add...

**Comment by carlidel** [comment]
I see!
Then it's for the best if I just delete this repo for now...
